<?php

namespace App\Console\Commands;

use BackedEnum;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use ReflectionEnum;
use SplFileInfo;

/**
 * Mirrors the PHP enums in app/Enums to TypeScript.
 *
 * The generated file is committed so the frontend type-checks without running the
 * command, but it must never be hand-edited: re-run this after changing any enum.
 */
class GenerateTypeScriptEnums extends Command
{
    protected $signature = 'unity:generate-ts-enums {--check : Fail if the generated file is out of date rather than writing it}';

    protected $description = 'Generate resources/js/types/enums.ts from the PHP enums in app/Enums';

    public const OUTPUT_PATH = 'resources/js/types/enums.ts';

    public function handle(): int
    {
        $enums = $this->enums();

        if ($enums === []) {
            $this->components->error('No backed enums found in app/Enums.');

            return self::FAILURE;
        }

        $contents = $this->render($enums);
        $path = base_path(self::OUTPUT_PATH);

        if ($this->option('check')) {
            if (File::exists($path) && File::get($path) === $contents) {
                $this->components->info(self::OUTPUT_PATH.' is up to date.');

                return self::SUCCESS;
            }

            $this->components->error(self::OUTPUT_PATH.' is out of date. Run: php artisan unity:generate-ts-enums');

            return self::FAILURE;
        }

        File::ensureDirectoryExists(dirname($path));
        File::put($path, $contents);

        $this->components->info(sprintf('Wrote %d enums to %s.', count($enums), self::OUTPUT_PATH));

        return self::SUCCESS;
    }

    /**
     * Every backed enum in app/Enums, keyed by short name.
     *
     * @return array<string, class-string<BackedEnum>>
     */
    protected function enums(): array
    {
        $enums = [];

        foreach (File::files(app_path('Enums')) as $file) {
            $class = $this->classFor($file);

            if (is_string($class) && enum_exists($class) && is_a($class, BackedEnum::class, true)) {
                $enums[class_basename($class)] = $class;
            }
        }

        ksort($enums);

        return $enums;
    }

    /** @return class-string|null */
    protected function classFor(SplFileInfo $file): ?string
    {
        $class = 'App\\Enums\\'.$file->getBasename('.php');

        return class_exists($class) || enum_exists($class) ? $class : null;
    }

    /**
     * @param  array<string, class-string<BackedEnum>>  $enums
     */
    protected function render(array $enums): string
    {
        $blocks = [];

        foreach ($enums as $name => $class) {
            $blocks[] = $this->renderEnum($name, $class);
        }

        return implode("\n", [
            '/**',
            ' * Generated by `php artisan unity:generate-ts-enums` — do not edit by hand.',
            ' *',
            ' * Mirrors the backed enums in app/Enums so the frontend compares against the',
            ' * same string values the backend sends over Inertia.',
            ' */',
            '',
            implode("\n", $blocks),
        ]);
    }

    /**
     * @param  class-string<BackedEnum>  $class
     */
    protected function renderEnum(string $name, string $class): string
    {
        $reflection = new ReflectionEnum($class);
        $isString = (string) $reflection->getBackingType() === 'string';

        $members = [];
        $values = [];

        foreach ($class::cases() as $case) {
            $value = $isString ? "'".addcslashes((string) $case->value, "'\\")."'" : $case->value;

            $members[] = sprintf('    %s: %s,', $case->name, $value);
            $values[] = $value;
        }

        return implode("\n", [
            sprintf('export const %s = {', $name),
            implode("\n", $members),
            '} as const;',
            '',
            sprintf('export type %s = (typeof %s)[keyof typeof %s];', $name, $name, $name),
            '',
            sprintf('export const %sValues: readonly %s[] = [%s];', lcfirst($name), $name, implode(', ', $values)),
            '',
        ]);
    }
}
