/**
 * Generated by `php artisan unity:generate-ts-enums` — do not edit by hand.
 *
 * Mirrors the backed enums in app/Enums so the frontend compares against the
 * same string values the backend sends over Inertia.
 */

export const ApportionmentItemStatus = {
    Pending: 'pending',
    Paid: 'paid',
    Cancelled: 'cancelled',
} as const;

export type ApportionmentItemStatus = (typeof ApportionmentItemStatus)[keyof typeof ApportionmentItemStatus];

export const apportionmentItemStatusValues: readonly ApportionmentItemStatus[] = ['pending', 'paid', 'cancelled'];

export const ApprovalStatus = {
    Pending: 'pending',
    PartiallyApproved: 'partially_approved',
    Approved: 'approved',
    Rejected: 'rejected',
} as const;

export type ApprovalStatus = (typeof ApprovalStatus)[keyof typeof ApprovalStatus];

export const approvalStatusValues: readonly ApprovalStatus[] = ['pending', 'partially_approved', 'approved', 'rejected'];

export const CollateralClaimStatus = {
    Draft: 'draft',
    CommitteeSignOff: 'committee_sign_off',
    Enforced: 'enforced',
    Released: 'released',
} as const;

export type CollateralClaimStatus = (typeof CollateralClaimStatus)[keyof typeof CollateralClaimStatus];

export const collateralClaimStatusValues: readonly CollateralClaimStatus[] = ['draft', 'committee_sign_off', 'enforced', 'released'];

export const CommitteeRole = {
    Chairperson: 'chairperson',
    ViceChairperson: 'vice_chairperson',
    Treasurer: 'treasurer',
    ViceTreasurer: 'vice_treasurer',
    Signatory: 'signatory',
} as const;

export type CommitteeRole = (typeof CommitteeRole)[keyof typeof CommitteeRole];

export const committeeRoleValues: readonly CommitteeRole[] = ['chairperson', 'vice_chairperson', 'treasurer', 'vice_treasurer', 'signatory'];

export const CycleMonthStatus = {
    Pending: 'pending',
    DeclarationsOpen: 'declarations_open',
    Trading: 'trading',
    Closed: 'closed',
} as const;

export type CycleMonthStatus = (typeof CycleMonthStatus)[keyof typeof CycleMonthStatus];

export const cycleMonthStatusValues: readonly CycleMonthStatus[] = ['pending', 'declarations_open', 'trading', 'closed'];

export const CycleStatus = {
    Draft: 'draft',
    Active: 'active',
    Closing: 'closing',
    ShareOut: 'share_out',
    Closed: 'closed',
} as const;

export type CycleStatus = (typeof CycleStatus)[keyof typeof CycleStatus];

export const cycleStatusValues: readonly CycleStatus[] = ['draft', 'active', 'closing', 'share_out', 'closed'];

export const DeclarationStatus = {
    Submitted: 'submitted',
    Approved: 'approved',
    Locked: 'locked',
    Processed: 'processed',
} as const;

export type DeclarationStatus = (typeof DeclarationStatus)[keyof typeof DeclarationStatus];

export const declarationStatusValues: readonly DeclarationStatus[] = ['submitted', 'approved', 'locked', 'processed'];

export const ExpulsionGround = {
    Dishonesty: 'dishonesty',
    Theft: 'theft',
    UnrulyBehavior: 'unruly_behavior',
    LoanMisconduct: 'loan_misconduct',
} as const;

export type ExpulsionGround = (typeof ExpulsionGround)[keyof typeof ExpulsionGround];

export const expulsionGroundValues: readonly ExpulsionGround[] = ['dishonesty', 'theft', 'unruly_behavior', 'loan_misconduct'];

export const FeeBearer = {
    Merchant: 'merchant',
    Customer: 'customer',
} as const;

export type FeeBearer = (typeof FeeBearer)[keyof typeof FeeBearer];

export const feeBearerValues: readonly FeeBearer[] = ['merchant', 'customer'];

export const FuneralRelationship = {
    Parent: 'parent',
    Spouse: 'spouse',
    Child: 'child',
} as const;

export type FuneralRelationship = (typeof FuneralRelationship)[keyof typeof FuneralRelationship];

export const funeralRelationshipValues: readonly FuneralRelationship[] = ['parent', 'spouse', 'child'];

export const GrantClaimStatus = {
    Submitted: 'submitted',
    Approved: 'approved',
    Paid: 'paid',
    Rejected: 'rejected',
} as const;

export type GrantClaimStatus = (typeof GrantClaimStatus)[keyof typeof GrantClaimStatus];

export const grantClaimStatusValues: readonly GrantClaimStatus[] = ['submitted', 'approved', 'paid', 'rejected'];

export const InterestAllocationMethod = {
    OwnSavingsFlat: 'own_savings_flat',
    PooledProRata: 'pooled_pro_rata',
} as const;

export type InterestAllocationMethod = (typeof InterestAllocationMethod)[keyof typeof InterestAllocationMethod];

export const interestAllocationMethodValues: readonly InterestAllocationMethod[] = ['own_savings_flat', 'pooled_pro_rata'];

export const LoanScheduleItemStatus = {
    Pending: 'pending',
    Paid: 'paid',
    PartiallyPaid: 'partially_paid',
    Missed: 'missed',
} as const;

export type LoanScheduleItemStatus = (typeof LoanScheduleItemStatus)[keyof typeof LoanScheduleItemStatus];

export const loanScheduleItemStatusValues: readonly LoanScheduleItemStatus[] = ['pending', 'paid', 'partially_paid', 'missed'];

export const LoanStatus = {
    Requested: 'requested',
    Approved: 'approved',
    Disbursed: 'disbursed',
    Repaying: 'repaying',
    Settled: 'settled',
    Defaulted: 'defaulted',
    Rejected: 'rejected',
} as const;

export type LoanStatus = (typeof LoanStatus)[keyof typeof LoanStatus];

export const loanStatusValues: readonly LoanStatus[] = ['requested', 'approved', 'disbursed', 'repaying', 'settled', 'defaulted', 'rejected'];

export const LoanTransactionType = {
    Disbursement: 'disbursement',
    InterestCharge: 'interest_charge',
    Repayment: 'repayment',
    LatePenaltyDaily: 'late_penalty_daily',
    MissedInstallmentPenalty: 'missed_installment_penalty',
    WriteOff: 'write_off',
} as const;

export type LoanTransactionType = (typeof LoanTransactionType)[keyof typeof LoanTransactionType];

export const loanTransactionTypeValues: readonly LoanTransactionType[] = ['disbursement', 'interest_charge', 'repayment', 'late_penalty_daily', 'missed_installment_penalty', 'write_off'];

export const MeetingType = {
    Monthly: 'monthly',
    Special: 'special',
    ShareOut: 'share_out',
} as const;

export type MeetingType = (typeof MeetingType)[keyof typeof MeetingType];

export const meetingTypeValues: readonly MeetingType[] = ['monthly', 'special', 'share_out'];

export const MemberRole = {
    Member: 'member',
    Treasurer: 'treasurer',
    ViceTreasurer: 'vice_treasurer',
    Chairperson: 'chairperson',
    ViceChairperson: 'vice_chairperson',
    Admin: 'admin',
} as const;

export type MemberRole = (typeof MemberRole)[keyof typeof MemberRole];

export const memberRoleValues: readonly MemberRole[] = ['member', 'treasurer', 'vice_treasurer', 'chairperson', 'vice_chairperson', 'admin'];

export const MemberStatus = {
    Active: 'active',
    LeftEarly: 'left_early',
    Expelled: 'expelled',
    Deceased: 'deceased',
} as const;

export type MemberStatus = (typeof MemberStatus)[keyof typeof MemberStatus];

export const memberStatusValues: readonly MemberStatus[] = ['active', 'left_early', 'expelled', 'deceased'];

export const MobileMoneyOperator = {
    Airtel: 'airtel',
    Mtn: 'mtn',
    Zamtel: 'zamtel',
} as const;

export type MobileMoneyOperator = (typeof MobileMoneyOperator)[keyof typeof MobileMoneyOperator];

export const mobileMoneyOperatorValues: readonly MobileMoneyOperator[] = ['airtel', 'mtn', 'zamtel'];

export const MotionType = {
    NoConfidence: 'no_confidence',
    Amendment: 'amendment',
    General: 'general',
} as const;

export type MotionType = (typeof MotionType)[keyof typeof MotionType];

export const motionTypeValues: readonly MotionType[] = ['no_confidence', 'amendment', 'general'];

export const NextOfKinRelationship = {
    Spouse: 'spouse',
    Parent: 'parent',
    Sibling: 'sibling',
    Child: 'child',
    Other: 'other',
} as const;

export type NextOfKinRelationship = (typeof NextOfKinRelationship)[keyof typeof NextOfKinRelationship];

export const nextOfKinRelationshipValues: readonly NextOfKinRelationship[] = ['spouse', 'parent', 'sibling', 'child', 'other'];

export const NotificationChannel = {
    Mail: 'mail',
    Sms: 'sms',
    Both: 'both',
} as const;

export type NotificationChannel = (typeof NotificationChannel)[keyof typeof NotificationChannel];

export const notificationChannelValues: readonly NotificationChannel[] = ['mail', 'sms', 'both'];

export const PaymentChannel = {
    MobileMoney: 'mobile_money',
    Card: 'card',
    BankAccount: 'bank_account',
} as const;

export type PaymentChannel = (typeof PaymentChannel)[keyof typeof PaymentChannel];

export const paymentChannelValues: readonly PaymentChannel[] = ['mobile_money', 'card', 'bank_account'];

export const PaymentDirection = {
    Collection: 'collection',
    Transfer: 'transfer',
} as const;

export type PaymentDirection = (typeof PaymentDirection)[keyof typeof PaymentDirection];

export const paymentDirectionValues: readonly PaymentDirection[] = ['collection', 'transfer'];

export const PaymentPurpose = {
    SavingsContribution: 'savings_contribution',
    DeclarationSettlement: 'declaration_settlement',
    JoiningFee: 'joining_fee',
    LoanRepayment: 'loan_repayment',
    SocialFundContribution: 'social_fund_contribution',
    LoanDisbursement: 'loan_disbursement',
    Payout: 'payout',
    ShareOut: 'share_out',
    FuneralGrant: 'funeral_grant',
    UnityBabyGrant: 'unity_baby_grant',
    DiasporaApportionment: 'diaspora_apportionment',
} as const;

export type PaymentPurpose = (typeof PaymentPurpose)[keyof typeof PaymentPurpose];

export const paymentPurposeValues: readonly PaymentPurpose[] = ['savings_contribution', 'declaration_settlement', 'joining_fee', 'loan_repayment', 'social_fund_contribution', 'loan_disbursement', 'payout', 'share_out', 'funeral_grant', 'unity_baby_grant', 'diaspora_apportionment'];

export const PaymentStatus = {
    Draft: 'draft',
    Pending: 'pending',
    AwaitingAuthorization: 'awaiting-authorization',
    Successful: 'successful',
    Settled: 'settled',
    Posted: 'posted',
    Failed: 'failed',
    Abandoned: 'abandoned',
    NeedsAttention: 'needs-attention',
} as const;

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];

export const paymentStatusValues: readonly PaymentStatus[] = ['draft', 'pending', 'awaiting-authorization', 'successful', 'settled', 'posted', 'failed', 'abandoned', 'needs-attention'];

export const PayoutCase = {
    ActiveShareOut: 'active_share_out',
    LeftEarly: 'left_early',
    Expelled: 'expelled',
    Deceased: 'deceased',
} as const;

export type PayoutCase = (typeof PayoutCase)[keyof typeof PayoutCase];

export const payoutCaseValues: readonly PayoutCase[] = ['active_share_out', 'left_early', 'expelled', 'deceased'];

export const PayoutDestinationType = {
    BankAccount: 'bank_account',
    MobileMoney: 'mobile_money',
} as const;

export type PayoutDestinationType = (typeof PayoutDestinationType)[keyof typeof PayoutDestinationType];

export const payoutDestinationTypeValues: readonly PayoutDestinationType[] = ['bank_account', 'mobile_money'];

export const PayoutLineKind = {
    Credit: 'credit',
    Debit: 'debit',
    Subtotal: 'subtotal',
    Adjustment: 'adjustment',
    Total: 'total',
    Note: 'note',
} as const;

export type PayoutLineKind = (typeof PayoutLineKind)[keyof typeof PayoutLineKind];

export const payoutLineKindValues: readonly PayoutLineKind[] = ['credit', 'debit', 'subtotal', 'adjustment', 'total', 'note'];

export const Permission = {
    MembersView: 'members.view',
    MembersManage: 'members.manage',
    SavingsView: 'savings.view',
    SavingsRecord: 'savings.record',
    DeclarationsView: 'declarations.view',
    DeclarationsSubmitOwn: 'declarations.submit-own',
    DeclarationsRecord: 'declarations.record',
    DeclarationsApprove: 'declarations.approve',
    TradingOperate: 'trading.operate',
    LoansView: 'loans.view',
    LoansRequest: 'loans.request',
    LoansApprove: 'loans.approve',
    LoansDisburse: 'loans.disburse',
    LoansRecordRepayment: 'loans.record-repayment',
    FundView: 'fund.view',
    FundRecord: 'fund.record',
    FundApproveOutflow: 'fund.approve-outflow',
    PayoutsApprove: 'payouts.approve',
    PayoutsExecute: 'payouts.execute',
    PaymentsView: 'payments.view',
    PaymentsInitiate: 'payments.initiate',
    PaymentsRetry: 'payments.retry',
    PaymentsReconcile: 'payments.reconcile',
    GovernanceRecord: 'governance.record',
    ReportsView: 'reports.view',
    AuditView: 'audit.view',
    CyclesManage: 'cycles.manage',
    CyclesCalendar: 'cycles.calendar',
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

export const permissionValues: readonly Permission[] = ['members.view', 'members.manage', 'savings.view', 'savings.record', 'declarations.view', 'declarations.submit-own', 'declarations.record', 'declarations.approve', 'trading.operate', 'loans.view', 'loans.request', 'loans.approve', 'loans.disburse', 'loans.record-repayment', 'fund.view', 'fund.record', 'fund.approve-outflow', 'payouts.approve', 'payouts.execute', 'payments.view', 'payments.initiate', 'payments.retry', 'payments.reconcile', 'governance.record', 'reports.view', 'audit.view', 'cycles.manage', 'cycles.calendar'];

export const SavingsTransactionType = {
    Contribution: 'contribution',
    JoiningFee: 'joining_fee',
    Adjustment: 'adjustment',
    ImportOpening: 'import_opening',
} as const;

export type SavingsTransactionType = (typeof SavingsTransactionType)[keyof typeof SavingsTransactionType];

export const savingsTransactionTypeValues: readonly SavingsTransactionType[] = ['contribution', 'joining_fee', 'adjustment', 'import_opening'];

export const SettlementStatus = {
    Outstanding: 'outstanding',
    Agreed: 'agreed',
    Settled: 'settled',
    WrittenOff: 'written_off',
} as const;

export type SettlementStatus = (typeof SettlementStatus)[keyof typeof SettlementStatus];

export const settlementStatusValues: readonly SettlementStatus[] = ['outstanding', 'agreed', 'settled', 'written_off'];

export const SocialFundTransactionType = {
    Contribution: 'contribution',
    LatePenaltyInflow: 'late_penalty_inflow',
    FuneralGrant: 'funeral_grant',
    UnityBabyGrant: 'unity_baby_grant',
    GatheringExpense: 'gathering_expense',
    DiasporaApportionment: 'diaspora_apportionment',
    Adjustment: 'adjustment',
} as const;

export type SocialFundTransactionType = (typeof SocialFundTransactionType)[keyof typeof SocialFundTransactionType];

export const socialFundTransactionTypeValues: readonly SocialFundTransactionType[] = ['contribution', 'late_penalty_inflow', 'funeral_grant', 'unity_baby_grant', 'gathering_expense', 'diaspora_apportionment', 'adjustment'];

export const TermEndReason = {
    TermEnd: 'term_end',
    Resigned: 'resigned',
    Removed: 'removed',
} as const;

export type TermEndReason = (typeof TermEndReason)[keyof typeof TermEndReason];

export const termEndReasonValues: readonly TermEndReason[] = ['term_end', 'resigned', 'removed'];

export const ThresholdBasis = {
    TotalMembers: 'total_members',
    MembersPresent: 'members_present',
} as const;

export type ThresholdBasis = (typeof ThresholdBasis)[keyof typeof ThresholdBasis];

export const thresholdBasisValues: readonly ThresholdBasis[] = ['total_members', 'members_present'];

export const TradingSessionStatus = {
    Open: 'open',
    Concluded: 'concluded',
} as const;

export type TradingSessionStatus = (typeof TradingSessionStatus)[keyof typeof TradingSessionStatus];

export const tradingSessionStatusValues: readonly TradingSessionStatus[] = ['open', 'concluded'];

export const TransactionSource = {
    Manual: 'manual',
    Trading: 'trading',
    Import: 'import',
    System: 'system',
    Gateway: 'gateway',
} as const;

export type TransactionSource = (typeof TransactionSource)[keyof typeof TransactionSource];

export const transactionSourceValues: readonly TransactionSource[] = ['manual', 'trading', 'import', 'system', 'gateway'];

export const WeekendTradingPolicy = {
    NextMonday: 'next_monday',
    PreviousFriday: 'previous_friday',
} as const;

export type WeekendTradingPolicy = (typeof WeekendTradingPolicy)[keyof typeof WeekendTradingPolicy];

export const weekendTradingPolicyValues: readonly WeekendTradingPolicy[] = ['next_monday', 'previous_friday'];
