/**
 * Generated by `php artisan unity:generate-ts-enums` — do not edit by hand.
 *
 * Mirrors the backed enums in app/Enums so the frontend compares against the
 * same string values the backend sends over Inertia.
 */

export const ApprovalStatus = {
    Pending: 'pending',
    PartiallyApproved: 'partially_approved',
    Approved: 'approved',
    Rejected: 'rejected',
} as const;

export type ApprovalStatus = (typeof ApprovalStatus)[keyof typeof ApprovalStatus];

export const approvalStatusValues: readonly ApprovalStatus[] = ['pending', 'partially_approved', 'approved', 'rejected'];

export const CycleMonthStatus = {
    Pending: 'pending',
    DeclarationsOpen: 'declarations_open',
    Trading: 'trading',
    Closed: 'closed',
} as const;

export type CycleMonthStatus = (typeof CycleMonthStatus)[keyof typeof CycleMonthStatus];

export const cycleMonthStatusValues: readonly CycleMonthStatus[] = ['pending', 'declarations_open', 'trading', 'closed'];

export const CycleStatus = {
    Draft: 'draft',
    Active: 'active',
    Closing: 'closing',
    Closed: 'closed',
} as const;

export type CycleStatus = (typeof CycleStatus)[keyof typeof CycleStatus];

export const cycleStatusValues: readonly CycleStatus[] = ['draft', 'active', 'closing', 'closed'];

export const ExpulsionGround = {
    Dishonesty: 'dishonesty',
    Theft: 'theft',
    UnrulyBehavior: 'unruly_behavior',
    LoanMisconduct: 'loan_misconduct',
} as const;

export type ExpulsionGround = (typeof ExpulsionGround)[keyof typeof ExpulsionGround];

export const expulsionGroundValues: readonly ExpulsionGround[] = ['dishonesty', 'theft', 'unruly_behavior', 'loan_misconduct'];

export const InterestAllocationMethod = {
    OwnSavingsFlat: 'own_savings_flat',
    PooledProRata: 'pooled_pro_rata',
} as const;

export type InterestAllocationMethod = (typeof InterestAllocationMethod)[keyof typeof InterestAllocationMethod];

export const interestAllocationMethodValues: readonly InterestAllocationMethod[] = ['own_savings_flat', 'pooled_pro_rata'];

export const MemberRole = {
    Member: 'member',
    Treasurer: 'treasurer',
    ViceTreasurer: 'vice_treasurer',
    Chairperson: 'chairperson',
    ViceChairperson: 'vice_chairperson',
    Admin: 'admin',
} as const;

export type MemberRole = (typeof MemberRole)[keyof typeof MemberRole];

export const memberRoleValues: readonly MemberRole[] = ['member', 'treasurer', 'vice_treasurer', 'chairperson', 'vice_chairperson', 'admin'];

export const MemberStatus = {
    Active: 'active',
    LeftEarly: 'left_early',
    Expelled: 'expelled',
    Deceased: 'deceased',
} as const;

export type MemberStatus = (typeof MemberStatus)[keyof typeof MemberStatus];

export const memberStatusValues: readonly MemberStatus[] = ['active', 'left_early', 'expelled', 'deceased'];

export const NextOfKinRelationship = {
    Spouse: 'spouse',
    Parent: 'parent',
    Sibling: 'sibling',
    Child: 'child',
    Other: 'other',
} as const;

export type NextOfKinRelationship = (typeof NextOfKinRelationship)[keyof typeof NextOfKinRelationship];

export const nextOfKinRelationshipValues: readonly NextOfKinRelationship[] = ['spouse', 'parent', 'sibling', 'child', 'other'];

export const Permission = {
    MembersView: 'members.view',
    MembersManage: 'members.manage',
    SavingsView: 'savings.view',
    SavingsRecord: 'savings.record',
    DeclarationsView: 'declarations.view',
    DeclarationsSubmitOwn: 'declarations.submit-own',
    LoansView: 'loans.view',
    LoansApprove: 'loans.approve',
    LoansDisburse: 'loans.disburse',
    LoansRecordRepayment: 'loans.record-repayment',
    FundApproveOutflow: 'fund.approve-outflow',
    PayoutsApprove: 'payouts.approve',
    PayoutsExecute: 'payouts.execute',
    GovernanceRecord: 'governance.record',
    ReportsView: 'reports.view',
    CyclesManage: 'cycles.manage',
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

export const permissionValues: readonly Permission[] = ['members.view', 'members.manage', 'savings.view', 'savings.record', 'declarations.view', 'declarations.submit-own', 'loans.view', 'loans.approve', 'loans.disburse', 'loans.record-repayment', 'fund.approve-outflow', 'payouts.approve', 'payouts.execute', 'governance.record', 'reports.view', 'cycles.manage'];

export const SavingsTransactionType = {
    Contribution: 'contribution',
    JoiningFee: 'joining_fee',
    Adjustment: 'adjustment',
    ImportOpening: 'import_opening',
} as const;

export type SavingsTransactionType = (typeof SavingsTransactionType)[keyof typeof SavingsTransactionType];

export const savingsTransactionTypeValues: readonly SavingsTransactionType[] = ['contribution', 'joining_fee', 'adjustment', 'import_opening'];

export const TransactionSource = {
    Manual: 'manual',
    Trading: 'trading',
    Import: 'import',
    System: 'system',
} as const;

export type TransactionSource = (typeof TransactionSource)[keyof typeof TransactionSource];

export const transactionSourceValues: readonly TransactionSource[] = ['manual', 'trading', 'import', 'system'];

export const WeekendTradingPolicy = {
    NextMonday: 'next_monday',
    PreviousFriday: 'previous_friday',
} as const;

export type WeekendTradingPolicy = (typeof WeekendTradingPolicy)[keyof typeof WeekendTradingPolicy];

export const weekendTradingPolicyValues: readonly WeekendTradingPolicy[] = ['next_monday', 'previous_friday'];
